esphome:
    name: "sht41-escritorio"
    friendly_name: "sensor de temperatura e humidade escritorio"
    platformio_options:
        board_build.flash_mode: dio

packages:
    - !include
        file: common/esp32-c6-mtd.yaml
        vars:
            openthread_tlv: !secret openthread_tlv
    - !include
        file: common/sht41.yaml

ota:
    - platform: esphome
      password: !secret ota_password
